# Generated by Django 2.1.3 on 2018-11-20 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advertisement_text', models.CharField(max_length=255)),
                ('Advertisement_data', models.FileField(upload_to='')),
                ('CreatedAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shop', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuickAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuickAdd_text', models.CharField(max_length=255)),
                ('QuickAdd_data', models.FileField(upload_to='')),
                ('CreatedAt', models.DateField(auto_now_add=True, db_index=True)),
                ('hash_tags', models.ManyToManyField(blank=True, to='market.HashTag')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopOwner', models.CharField(max_length=255)),
                ('ShopName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('NumOfAds', models.IntegerField()),
                ('NumOfQuickAds', models.IntegerField()),
                ('ProfilePic', models.ImageField(upload_to='profilePics/')),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('hash_tags', models.ManyToManyField(to='market.HashTag')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, unique=True)),
                ('allowed_hash_tags', models.ManyToManyField(to='market.HashTag')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ShopCategory'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickadd',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Shop'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, to='market.HashTag'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Shop'),
        ),
    ]
