# Generated by Django 2.1.3 on 2018-11-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='Advertisement_data',
            field=models.ImageField(upload_to='adds/'),
        ),
    ]
