# Generated by Django 2.1.3 on 2018-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20181120_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickadd',
            name='QuickAdd_data',
            field=models.ImageField(upload_to='quick_adds/'),
        ),
    ]
